### ISSUE TITLE
Relatives section - overall validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1263]
Criteria for overall section validation - these would appear on the review screen:

- [ ] Mother and Father must be checked, or else DNK and a Comment on 2nd pass. 
- [ ] Mother-in-law and Father-in-law must be checked if marital status is "Married" or "Separated", or else DNK and a Comment on 2nd pass. 
- [ ] Mother-in-law and Father-in-law not allowed if marital status is "Never Married".

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
