### ISSUE TITLE
Relatives - Countries of citizenship - Validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1267]
- [ ] Response is required

-
<img width="974" alt="screen shot 2017-05-22 at 1 00 35 pm" src="https://cloud.githubusercontent.com/assets/19935974/26319863/ad80152e-3eee-11e7-8b88-a0dcf70a358f.png">

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
