### ISSUE TITLE
Relatives - Other names used - Validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1270]
- [ ] Response is required if relative type is:
Father
or
Child
or
Stepchild
or
Brother
or
Sister
or
HalfBrother
or
HalfSister
or
Stepbrother
or
Stepsister
or
Stepmother
or
Stepfather

-
Other names used details validation: 
Full name block:
- [ ] Response is required

Maiden name:
- [ ] Response is required

Dates used:
- [ ] Response is required
- [ ] Format: MM/YYYY

From date:
- [ ] Ensure valid date, no future date allowed. 
- [ ] Date must be greater than or equal to "Your relative's date of birth

To date:
- [ ] Ensure valid date greater than or equal to From Date. 
- [ ] Date must be less than or equal to NOW. "Present" allowed instead of date

Has this relative used any additional names?:
- [ ] Response is required

- [ ] Add additional comment to this section at bottom

-
<img width="919" alt="screen shot 2017-05-22 at 1 12 32 pm" src="https://cloud.githubusercontent.com/assets/19935974/26320288/5aa5bcbc-3ef0-11e7-9e92-a9b02099a789.png">
<img width="890" alt="screen shot 2017-05-22 at 1 12 26 pm" src="https://cloud.githubusercontent.com/assets/19935974/26320289/5aaae44e-3ef0-11e7-9429-a936a3a458d4.png">
<img width="903" alt="screen shot 2017-05-22 at 1 29 15 pm" src="https://cloud.githubusercontent.com/assets/19935974/26320902/ad1a5226-3ef2-11e7-923f-74e865451907.png">
<img width="900" alt="screen shot 2017-05-22 at 1 29 21 pm" src="https://cloud.githubusercontent.com/assets/19935974/26320903/ae7e3114-3ef2-11e7-97f4-3adf5626f4fa.png">

**Comment by Jay-Neighbours-I72** [comment]
Looks like currently this is using the user's DOB instead of the relative's.


![screen shot 2018-01-10 at 11 47 01 am](https://user-images.githubusercontent.com/19935974/34784344-fea39272-f5fb-11e7-964b-4a06ec11e940.jpg)

![screen shot 2018-01-10 at 11 46 27 am](https://user-images.githubusercontent.com/19935974/34784328-f3cbccf2-f5fb-11e7-8eaa-4267af6d1edb.jpg)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
