### ISSUE TITLE
Relatives - Deceased question

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1274]
- [ ] Response is required if relative type is:
Foster parent
or
Father in law
or
Mother in law
or 
Guardian
or
Answered "No" to relative using any other names

-
<img width="915" alt="screen shot 2017-05-22 at 1 52 12 pm" src="https://cloud.githubusercontent.com/assets/19935974/26321699/de8a6b72-3ef5-11e7-97c3-2d0f8a08cb9e.png">

**Comment by bmallred** [comment]
There was some conversation about this question as well because quite a few people who fill out the form do not actually know if the relative is deceased. When on this task maybe take a look at verbiage, adding an "I don't know" type of response, or comments.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
