### ISSUE TITLE
Address block - Validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1277]
In US:
ZIP Code:
- [ ] Ensure numerics (5 or 10 digits, if 10 digits hyphen must be the 6th character). 
- [ ] Validate that first 3 digits match State.

-
APO/FPO:
State:
- [ ] Military states only as allowed values.

ZIP Code:
- [ ] Ensure numerics (5 or 10 digits, if 10 digits hyphen must be the 6th character). 
- [ ] Validate that first 3 digits match State.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
