### ISSUE TITLE
Relatives - Foreign relative's employer, Foreign military affiliation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1281]
Name of current employer, or provide the name of their most recent employer:
- [ ] Response or "I don't know" is required

Address of current employer:
- [ ] Response or "I don't know" is required
<img width="888" alt="screen shot 2017-05-22 at 3 46 03 pm" src="https://cloud.githubusercontent.com/assets/19935974/26325652/c6a81292-3f05-11e7-8639-15847afa7ebc.png">

-
Foreign Military Affiliation:
- [ ] Response is required

Foreign Military Affiliation - Detail:
- [ ] Response is required

Do you have an additional relative to enter?:
- [ ] Response is required

<img width="884" alt="screen shot 2017-05-22 at 3 48 13 pm" src="https://cloud.githubusercontent.com/assets/19935974/26325727/134ded7e-3f06-11e7-9a93-742b46e78435.png">

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
