### ISSUE TITLE
Foreign activities - Direct control - Yes/No buttons within accordions

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1314]
Yes/No buttons that create branches inside accordion are not functioning properly.

When Yes is selected and user clicks No:
Yes is deselected but No isn't selected, user has to click No again to select it.

<img width="713" alt="screen shot 2017-05-26 at 9 44 52 am" src="https://cloud.githubusercontent.com/assets/19935974/26497182/7920c2bc-41f8-11e7-900a-da865a5978bf.png">
<img width="774" alt="screen shot 2017-05-26 at 9 45 01 am" src="https://cloud.githubusercontent.com/assets/19935974/26497183/7a27a860-41f8-11e7-8b23-f122a40c5bc8.png">

**Comment by floresj** [comment]
When a user selects Yes for a branch collection, we add another yes/no branch with the repeating question. For instance, if a user sees the branch collection for the first time, they'll see the following:

### Scenario 1 
Question
[Yes] [No]


### Scenario 2 
Now, assume the user selects Yes, we highlight yes and then add another blank yes/no branch.

Question
**[Yes]** [No]

Question
[Yes] [No]

### Scenario 3
Now, when a user selects **No**, we delete the content for that particular set of data. So in scenario 2, if a user selects No, it's removing the content and yes/no branch which then shifts the second yes/no branch to the first spot. 

What I'll do is if a user selects No and it's the second to last option, then leave the last item marked as No.

**Comment by billy22g** [comment]
Oh wow, this one is super interesting. @Jay-Neighbours-I72 Do you think if they've filled stuff out, then go back and answer "No" to the very first question, that we should keep the second one? Seems like the first question is an absolute "Are there any at all?" and if they go back and answer "No" that means delete all of them. Thoughts? cc: @lauraponce

**Comment by Jay-Neighbours-I72** [comment]
I agree that logically it should remove everything in that branch. 

A message explaining that might be useful though ("Switching your answer to No here will remove your answers...etc"
or something along those lines

**Comment by billy22g** [comment]
Love that idea. Let's do it. So a "No" on the initial question removes everything in the branch, but doing that when "Yes" is selected and there's info in any of the fields pops a confirm that they have to confirm the action.

**Comment by billy22g** [comment]
@floresj Let us know if that doesn't make sense.

**Comment by bmallred** [comment]
Had a discussion with @Jay-Neighbours-I72 and @floresj which came to these potential changes:

 1. Confirmation on "No" (similar to "Remove" on the accordion)
 2. Transition animation on "Yes" expanding the content downwards
 3. Transition animation on "No" (and subsequent confirmation) collapsing the content towards the current element

The thought process was to try and help draw attention to what is actually happening similar to how the accordion visually informs the user of the current item being added (etc.). 

@billy22g all of this mesh with the direction above?

**Comment by billy22g** [comment]
Yep, works for me!

**Comment by Jay-Neighbours-I72** [comment]
Not seeing this one as done. There is some weird scrolling happening and no confirmation when switching an answer to "No"

@floresj @bmallred

**Comment by floresj** [comment]
@Jay-Neighbours-I72 I don't think we've started working on incorporating that functionality into the branch collection yet.

**Comment by Jay-Neighbours-I72** [comment]
Want me to move back to in progress?

**Comment by floresj** [comment]
Just moved it back :+1:

**Comment by bmallred** [comment]
Should this be moved back to QA because of issue #1464 and pull request #1503?

cc: @Jay-Neighbours-I72 @floresj

**Comment by Jay-Neighbours-I72** [comment]
This does seem like a duplicate of #1464

The question of still throwing the warning when fields are empty is still open though right?

**Comment by bmallred** [comment]
Yes, and that won't be fixed this iteration more than likely because it is a much more complex issue and one which we haven't been planning.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 is this behaving as expected now?

**Comment by bmallred** [comment]
Looks like this may have been resolved.

**Comment by billy22g** [comment]
I'm not seeing this as resolved. If I say "Yes" and then "Yes" again, and go back and change the answer to the first question to "No," only the first one goes away. As discussed above, it should also remove the entry from the second one, because the person is effectively saying "There are no co-owners." Right @Jay-Neighbours-I72?

**Comment by Jay-Neighbours-I72** [comment]
I see what you are saying here @billy22g , that is kind of confusing when switching a branch to No and the next one bumps up. It almost looks like nothing was deleted.

The original point of having a single click to switch from Yes to No in this ticket is resolved.

But the confusion around deleting one may be a bigger issue.

Maybe adding a dividing line and small header for each new branch (in this case co-owner) would help clarify? Older comp style shown below, we were using them for phone numbers in this example:

<img width="1226" alt="screen shot 2017-08-25 at 9 42 05 am" src="https://user-images.githubusercontent.com/19935974/29716675-3cd0b794-897a-11e7-8819-ad790a6b374d.png">

**Comment by bmallred** [comment]
I'm going to move this back to the task list until we know for sure what the desired outcome is.

**Comment by billy22g** [comment]
Thanks Bryan. Let's bring it up during the next standup that Sheldon is on for a decision.

**Comment by pjsumm** [comment]
Team reviewed and will revisit.  need to better define the problem and potential resolutions.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
