### ISSUE TITLE
Relatives - Branching logic incorrect

### ISSUE THREAD

**Issue by billygriffin** [ryanhofdotgov/e-QIP-prototype-truetandem#1320]
<img width="645" alt="screen shot 2017-05-30 at 8 17 08 am" src="https://cloud.githubusercontent.com/assets/5091167/26587767/7e5d9000-4510-11e7-99dc-24c2878c329f.png">

If they are not a U.S. citizen and they're not deceased, they should be shown the "Current Employer" fields and foreign govt affiliation question. Those are outside the scope of the current address being outside the U.S., but are currently only shown if they select that their address is outside the U.S.

**Comment by billy22g** [comment]
This leaves out the state and zip (shown in the above PDF) if in US, and country if not.

**Comment by floresj** [comment]
@billy22g I'm thinking of changing this to use the full address component which includes APO/FPO address. Would there be any issues with allowing users to include APO/FPO for this particular case?

cc: @Jay-Neighbours-I72

**Comment by billy22g** [comment]
@floresj That's a question for @Sheldon1013 and @DBrenenborg because the form doesn't have any space for APO/FPO. However, it is reasonable for someone's employer address to be an APO or FPO address, so it seems like it could be a reasonable approach. Can you bring it up as a question in standup or sprint review please? cc: @colinpmacarthur

**Comment by bmallred** [comment]
@floresj can you ping @DBrenenborg or @Sheldon1013 on this?

**Comment by billy22g** [comment]
Per Sheldon, use the resusable address field (@Jay-Neighbours-I72, please add this to content tracking doc).

**Comment by floresj** [comment]
Based on bug discussion, change to use full address component for employer address but ensure to only send subset of info to eqip.

**Comment by pjsumm** [comment]
While the address fields have been changed to full addresses, we are using APO/FPO/DPO on their home address and not their work address.  Based on comments above, which I agree with, we should either have both using APO/FPO/DPO for consistency or just have it on work address, not home.  @billy22g, I'm curious to get your take.

**Comment by bmallred** [comment]
For additional reference the APO/DPO was removed from the employer address due to this issue (per Donna): https://github.com/truetandem/e-QIP-prototype/issues/2332

**Comment by billy22g** [comment]
Yeah, I *think* I understand this but not 100% sure. My thinking is that it should match what Donna gave the ok on in the other issue if they’re sufficiently similar. It’s annoying to have variation, but if it’s a departure from the form, let’s try to stay consistent in how we depart. That make sense? We can discuss after standup as well.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
