### ISSUE TITLE
Remove pa11y from CI

### ISSUE THREAD

**Issue by bmallred** [ryanhofdotgov/e-QIP-prototype-truetandem#1428]
Try to find something to replace the functionality used with pa11y.

**Comment by bmallred** [comment]
Investigating integrating `pa11y` or the `HTML_CodeSniffer` (which `pa11y` uses) with our unit tests.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
