### ISSUE TITLE
Foreign activities - Foreign national sponsorship - Address blocks

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1554]
Two address blocks in this section:
1. Foreign national's current address
2. Sponsoring organization address

I'm thinking neither of these need the APO/FPO address inputs. Is that correct?

**Comment by bmallred** [comment]
@Sheldon1013 mentioned to not include APO/FPO for now on these.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
