### ISSUE TITLE
Explain distance between residence and job

### ISSUE THREAD

**Issue by pjsumm** [ryanhofdotgov/e-QIP-prototype-truetandem#1573]
As an eApp applicant I want to be prompted to provide an explanation for why my home is far away from my work or school so that my investigator understands the circumstances for the distance (telework, online classes, incorrect job office used)

Acceptance Criteria
- distance between work and residence over TBD miles
- distance between work and school TBD miles
- user is prompted to provide explanation

**Comment by pjsumm** [comment]
leverage addresses for calculations if possible, or zip codes.  Need to find an API for distance calculations

example message:  Your residence is x miles from your school/place of work.  Did you use the correct physical work location?  Please provide an explanation,

**Comment by pjsumm** [comment]
Research potential ways to determine if work location and residence are far apart.

**Comment by bmallred** [comment]
Potential avenues to research:

 - Adjacent state
 - Geo-coding and distance calculation

**Comment by floresj** [comment]
Postgres has geospatial functions (http://postgis.net/) that can perform different calculations given we have geocoded information.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
