### ISSUE TITLE
Substance use - Usage - Validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1678]
Estimate of the month and year of first use:
- [x] Date must be greater than or equal to DOB

Estimate of the month and year of most recent use:
- [ ] Date must be greater than or equal to "Estimate of the month and year of first use

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
