### ISSUE TITLE
Substance use - Purchase - validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1683]
Estimate for the month and year of first involvement:
- [x] Date must be greater than or equal to DOB

Estimate for the month and year of most recent involvement:
- [ ] Date must be greater than or equal to "Estimate for the month and year of first involvement

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
