### ISSUE TITLE
Use of alcohol - Negative impact - Validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1694]
Dates of involvement or use:
From date:
- [x] Date must be greater than or equal to DOB

To date:
- [ ] Ensure valid date greater than or equal to From Date

Month/year when this negative impact occurred:
- [ ] Date must be greater than or equal to "Dates of involvement or use"  From Date

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
