### ISSUE TITLE
Use of alcohol - Mandatory counseling or treatment - Validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1696]
Dates of counseling or treatment:
From date:
- [x] Date must be greater than or equal to DOB

To date:
- [ ] Ensure valid date greater than or equal to From Date

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
