### ISSUE TITLE
Section 1 - Contact Information

### ISSUE THREAD

**Issue by TravisAJackson** [ryanhofdotgov/e-QIP-prototype-truetandem#1722]
Area Code 000 is invalid but no error given.
![image](https://user-images.githubusercontent.com/30842622/29173172-7125c500-7db0-11e7-8384-0c6f73532276.png)

**Comment by bmallred** [comment]
There was no error message because it is deemed **valid** according to the regular expression applied. Probably should do some additional validation similar to #1732

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
