### ISSUE TITLE
Section 1 - Contact Information - International Number

### ISSUE THREAD

**Issue by TravisAJackson** [ryanhofdotgov/e-QIP-prototype-truetandem#1732]
Invalid numbers accepted. See ISO standards.

![image](https://user-images.githubusercontent.com/30842622/29278503-ee5f018c-80e2-11e7-982d-6f2c3d7f7aa8.png)

**Comment by bmallred** [comment]
Assuming the ISO referenced is ISO-3166

Reference: 
 - http://www.nationsonline.org/oneworld/country_code_list.htm
 - https://en.wikipedia.org/wiki/ISO_3166-1
 - https://en.wikipedia.org/wiki/ISO_3166-1_numeric

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
