### ISSUE TITLE
Section 1 - SSN

### ISSUE THREAD

**Issue by TravisAJackson** [ryanhofdotgov/e-QIP-prototype-truetandem#1742]
Invalid use of SSN.
123 45 6789 is not allowed.

![image](https://user-images.githubusercontent.com/30842622/29281320-93d9d02a-80ec-11e7-9541-27ff9bf815fd.png)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
