### ISSUE TITLE
Investigations and clearance record - Ever been investigated - Validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#1801]
Date the investigation was completed:
- [x] Date must be greater than or equal to DOB

Date clearance eligibility/access was granted:
- [ ] Date must be greater than or equal to both DOB and "Date the investigation was completed

**Comment by TravisAJackson** [comment]
Jay I created a global ticket for all dates comparable to DOB validation. Also date items that have a to and from ("I went to school 99/00 but I received a degree in 88").

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
