### ISSUE TITLE
Email applicant to register

### ISSUE THREAD

**Issue by pjsumm** [ryanhofdotgov/e-QIP-prototype-truetandem#1880]
As an eApp developer I want to create a service to generate emails to prospective eApp applicants containing a link to their respective eApp registration page so that they can access the URL containing their registration code to register for a user account. 

Acceptance Criteria: 
- [ ] Generate email to send to the applicant's email address
- [ ] Ensure the email contains a URL with the user's registration code embedded

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
