### ISSUE TITLE
Review Design

### ISSUE THREAD

**Issue by pjsumm** [ryanhofdotgov/e-QIP-prototype-truetandem#1984]
As an eApp designer I want to review the styles and layout of the SF86 form so that I can verify that the styles are consistent across all sections

Acceptance Criteria

**Comment by billy22g** [comment]
Retro link: http://piratepad.net/6AtnJPlJl8

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
