### ISSUE TITLE
Consolidating repositories instead of maintaining 18F and TT

### ISSUE THREAD

**Issue by bmallred** [ryanhofdotgov/e-QIP-prototype-truetandem#2016]
Discuss changing the workflow to use the `18F` repository instead of using the `truetandem` fork and then pushing updates to the `18F` repository.

**Comment by ctro** [comment]
This would simplify a couple things:

1. The review process.  Review would go between staging -> master instead of across repos.
2. CircleCI builds. Circle only supports filtering on branches, and that's problematic when we both have master branches.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
