### ISSUE TITLE
Print working copy at any time within the application

### ISSUE THREAD

**Issue by bmallred** [ryanhofdotgov/e-QIP-prototype-truetandem#2065]
At any moment within the application I would like the ability to print a "working copy" of the form and the content currently entered.

**Comment by billy22g** [comment]
Is this actually something we might want to do down the road? I haven't heard a use case for this, and thought NBIB actively discourages it.

**Comment by bmallred** [comment]
This was brought up in multiple meetings where they stating they could print a "working copy". However we had moved it to the icebox b/c we weren't sure if it was going to be a requirement at some point I believe.

**Comment by Jay-Neighbours-I72** [comment]
Could the print functionality be used for this?

**Comment by billy22g** [comment]
We just need to verify that this is actually a need. I don’t think it’s delivering user value, and I would suspect Sheldon would agree.

________________________________

**Comment by Jay-Neighbours-I72** [comment]
I agree with it not adding much value. To me navigating back to the sections is the review. 

1 user from usability testing mentioned wanting it at the end of the form. The didn't mention wanting to review at any point while filling out though.

**Comment by pjsumm** [comment]
Reviewed.  Team determined this is needed, but is a lower priority.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
