### ISSUE TITLE
Phone - save button not showing on all screens

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2109]
- [ ] Save button isn't showing on all screens

<img width="376" alt="screen shot 2017-10-23 at 3 52 16 pm" src="https://user-images.githubusercontent.com/19935974/31910049-3720efd0-b80a-11e7-85d7-07650059bad8.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 is this still happening on said device? Not able to reproduce currently on my devices.

**Comment by Jay-Neighbours-I72** [comment]
@bmallred yeah I'm still seeing it on my phone

![8cf27a92-7fa1-47c9-9d89-77ac9f580b7e](https://user-images.githubusercontent.com/19935974/37428357-5f378a76-27a2-11e8-9c51-322cee95a44a.jpg)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
