### ISSUE TITLE
Update deploy script to automatically delete venerable apps

### ISSUE THREAD

**Issue by ctro** [ryanhofdotgov/e-QIP-prototype-truetandem#2193]
Venerable apps don't always get deleted, and this causes problems with deploys.
Here's an example of how another project deletes Venerable apps in their deploy script:

https://github.com/18F/fs-intake-module/blob/master/cg-deploy/deploy.sh#L46

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
