### ISSUE TITLE
Obtain content approval from NBIB Policy

### ISSUE THREAD

**Issue by billygriffin** [ryanhofdotgov/e-QIP-prototype-truetandem#2249]
As a user, I want my SF86 form to be legally compliant with the approved SF86 so that I have confidence that the form will be processed properly.

Acceptance criteria:

- [x] Document tracking departures from layout of SF86 Content Guide completed
- [x] Laura review
- [ ] Billy review
- [ ] Drew review
- [ ] Sheldon review
- [ ] NBIB Policy review

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
