### ISSUE TITLE
Incorporate git-seekret

### ISSUE THREAD

**Issue by bmallred** [ryanhofdotgov/e-QIP-prototype-truetandem#2253]
Taken from @anthonygarvan's [this comment](https://github.com/18F/e-QIP-prototype/pull/105#discussion_r154097153):

> For the future I would recommend you & team installing 18F's git-seekrets to prevent leaking sensitive info, available [here](https://github.com/18F/git-seekret). It works well, hooks into git's commit command and scans the commit for various patterns.

Reference package [git-seekret](https://github.com/18F/git-seekret)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
