### ISSUE TITLE
Individual asterisks on inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2361]
Few locations that still need individual asterisks:

- [ ] Place of birth & all location blocks like this:
![screen shot 2018-01-04 at 3 42 40 pm](https://user-images.githubusercontent.com/19935974/34583493-edd0241e-f165-11e7-91ae-504ad74fee16.png)
![screen shot 2018-01-04 at 3 45 26 pm](https://user-images.githubusercontent.com/19935974/34583591-4ec8f944-f166-11e7-88a3-9fd42c54372d.png)
![screen shot 2018-01-04 at 3 49 22 pm](https://user-images.githubusercontent.com/19935974/34583746-dfaabe48-f166-11e7-93a9-06d76f17cc62.png)

- [ ] Height and weight:
![screen shot 2018-01-04 at 3 43 42 pm](https://user-images.githubusercontent.com/19935974/34583558-3040725e-f166-11e7-8b7f-745074d6c2fa.png)

@bmallred @floresj Thoughts on switching the asterisks to the label when it is there across the form?

**Comment by bmallred** [comment]
@Jay-Neighbors-I72 definitely easier said than done. We'll have to go through each potential use case and explicitly set it.

**Comment by bmallred** [comment]
From #2327

- [ ] Put individual asterisks on date blocks (month, day, year)

![screen shot 2017-12-18 at 2 45 58 pm](https://user-images.githubusercontent.com/19935974/34124813-4c6fb9a6-e402-11e7-8983-c36f45f75b39.jpg)

**Comment by bmallred** [comment]
From #2203 

Put asterisks on individual input field on all address blocks.

Example Place of Birth (want asterisks on City, State, & County)
![screen shot 2017-11-17 at 10 20 44 am](https://user-images.githubusercontent.com/19935974/32954484-3d06d3a8-cb81-11e7-89c7-f6df7de96941.jpg)

like in the full address block:
![screen shot 2017-11-17 at 10 21 18 am](https://user-images.githubusercontent.com/19935974/32954497-44929b3e-cb81-11e7-914f-6dd8e78bcf31.jpg)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
