### ISSUE TITLE
Safari - US military buttons - can't select

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2395]
- [ ] Can't select the military branch or enlisted buttons:

![screen shot 2018-01-12 at 11 48 57 am](https://user-images.githubusercontent.com/19935974/34885692-d113007e-f78e-11e7-9afc-eeca659dfcec.jpg)

Also happening in other sections. looks like the selection is being made but not showing to the user:
![screen shot 2018-01-12 at 11 57 45 am](https://user-images.githubusercontent.com/19935974/34886042-df9301f2-f78f-11e7-90a8-b00fbf1be04c.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Also happening in Firefox

![screen shot 2018-01-15 at 2 44 47 pm](https://user-images.githubusercontent.com/19935974/34959078-a5e6bfb4-fa02-11e7-89ed-caa5c6f9324f.jpg)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
