### ISSUE TITLE
Firefox - Extension input on phone numbers misaligned 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2401]
- [ ] Extension input on phone numbers box is misaligned 

![screen shot 2018-01-12 at 4 05 50 pm](https://user-images.githubusercontent.com/19935974/34895196-95a9427c-f7b2-11e7-9703-1bf4ae19c7d4.jpg)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
