### ISSUE TITLE
Firefox - Accordions

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2403]
- [ ] Adding a new accordion item - new item doesn't start at the top of the screen, starts part way down

![screen shot 2018-01-15 at 10 06 51 am](https://user-images.githubusercontent.com/19935974/34948752-0ea250d0-f9dc-11e7-82f4-952a0f8bf772.jpg)

**Comment by bmallred** [comment]
Probably not a firefox issue but one just in general.

**Comment by Jay-Neighbours-I72** [comment]
@bmallred I was only seeing it Firefox, was working in Chrome

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
