### ISSUE TITLE
Saved Button 

### ISSUE THREAD

**Issue by gshannon00** [ryanhofdotgov/e-QIP-prototype-truetandem#2484]
**What did you do?**
Clicked on Next Relationships Into button. The Saved button showed Saved Just Now, but within 5 seconds the Saved button showed Saved 18 minutes ago. So, was the data Saved Just Now, or was it saved 18 Minutes ago. 
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
The Saved clock to start over if the data was Saved Just Now
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**

*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35346677-de5566a2-0100-11e8-84e1-edc7a24a3b36.png)
![image](https://user-images.githubusercontent.com/31284016/35346707-eb9493c4-0100-11e8-8481-8ffb9540d13b.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
@bmallred is the save button functional currently or still waiting to be hooked in?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 the save button timer is reset when persisting to the backend. So currently when the button is pressed or between navigating of sections.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
