### ISSUE TITLE
DPO

### ISSUE THREAD

**Issue by gshannon00** [ryanhofdotgov/e-QIP-prototype-truetandem#2495]
**What did you do?**
Chose DPO for an address
*Including steps for recreating it, if applicable.*

**What did you expect to see?**

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
There is not 'DPO' choice in the current e-QIP; this field will not transition over if an applicant chooses it. 
**What did you see instead?**

*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35353964-c5a5cd70-0116-11e8-8e7c-bcd6c6ee3918.png)

 - What browser and version are you using?
 - What operating system?

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Should we just remove the `DPO` option then? This is a trivial update.

**Comment by Jay-Neighbours-I72** [comment]
Do you or @bmallred remember who requested to add DPO? I don't.

**Comment by floresj** [comment]
I remember adding it at one point just because it was easy to add and noticed it was an option when I was verifying APO/FPO formats on the USPS site.

**Comment by bmallred** [comment]
This was from early days where things weren't as recorded as they are now. If my fuzzy old man logic is correct it was along the lines of "it is a valid address designation and USPS allows it so we'll use it". As far as who said I have no idea, so I'll take the hit for it :smiling_imp:

**Comment by Jay-Neighbours-I72** [comment]
I was mainly curious if this was something Sheldon asked for or not. I'm good with keeping or losing it. Let's make sure Sheldon is good with it too on a stand up at some point.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
