### ISSUE TITLE
Resize military icons so they load faster

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2496]
Suggest using smaller images to prevent the slow loading we are seeing

**Comment by Jay-Neighbours-I72** [comment]
Icons resized and dropped in google drive:
https://drive.google.com/drive/folders/1rHmHC-B1xS5O2vkdlVTDENid2-QlhRgK?usp=sharing

**Comment by bmallred** [comment]
**Note**: We need to check if any of these new images have special styling applied as well. If so we need to update there contents within `<Svg/>`

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
