### ISSUE TITLE
Email address of Separated Spouse

### ISSUE THREAD

**Issue by gshannon00** [ryanhofdotgov/e-QIP-prototype-truetandem#2502]
**What did you do?**
Left the email address field blank for a separated spouse 
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
 I didn't expect it to be a mandatory field
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
The email address for the separated spouse has an asterisk which means it is a mandatory field. The applicant is legally separated from the spouse; what if the email address is Unknown? 
**What did you see instead?**

*Include a high-level description of the feature or error here*

**Additional Information**
If the applicant provided a telephone number, why is the email address required? 
*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35400876-fe9d5008-01c5-11e8-95ca-df7dcba11639.png)

 - What browser and version are you using?
 - What operating system?

**Comment by bmallred** [comment]
That is a valid point. Below is a screenshot from the content guide. Typically if it does not say it is optional (or something similar in verbiage) we defaulted it to required. Going to mark this for review during our next grooming session.

cc: @Jay-Neighbours-I72 @billy22g @lauraponce @pjsumm 

![image](https://user-images.githubusercontent.com/697855/35442824-9ae51a44-0276-11e8-9fac-713723dd6484.png)

**Comment by Jay-Neighbours-I72** [comment]
Agreed @bmallred , our assumption was it was required.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
