### ISSUE TITLE
Redundant Info Block

### ISSUE THREAD

**Issue by gshannon00** [ryanhofdotgov/e-QIP-prototype-truetandem#2503]
**What did you do?**
Opened the info bloc for Provide Date of Separation
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
A description of what a separation date is. 
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
The info block is redundant, not needed. The question is Provide Date of Separation, open the Info Block and it states Provide the Date of Separation. 
**What did you see instead?**
Redundant information
*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35401505-b8d7e630-01c7-11e8-94c7-11e2ce2a0f44.png)

 - What browser and version are you using?
 - What operating system?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 what do you think?

**Comment by Jay-Neighbours-I72** [comment]
I agree that this doesn't make a ton of sense.

Looks like the content guide did this so Marriage, civil union, domestic partnership, and separated could all be in the same branch.

Like much of the form content I think this could be improved greatly, not sure where/when we should tackle it though. Maybe this is something we add to a proposed content update doc.

Good idea to add question tag and talk through with team.


![screen shot 2018-01-26 at 9 48 05 am](https://user-images.githubusercontent.com/19935974/35445028-54fcc948-027e-11e8-9040-68cb72cd7400.jpg)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
