### ISSUE TITLE
Relatives - Method of contact - Other block

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2519]
- [ ] Use a separate comment block for the "Other" answer

![screen shot 2018-01-26 at 2 38 59 pm](https://user-images.githubusercontent.com/19935974/35457508-2caa1daa-02a7-11e8-967d-ad31cd3553f8.jpg)
![screen shot 2018-01-26 at 2 39 06 pm](https://user-images.githubusercontent.com/19935974/35457510-2cb45cb6-02a7-11e8-96ee-67fe10b49301.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 the frequency block has a similar situation. Change that one as well?

![image](https://user-images.githubusercontent.com/697855/37299539-fe10699c-25f9-11e8-9e52-086c9e1f5673.png)

**Comment by Jay-Neighbours-I72** [comment]
@bmallred Good catch, yes.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
