### ISSUE TITLE
IE11 - extra space below content

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2521]
- [x] Extra space below main content

![screen shot 2018-01-26 at 2 53 37 pm](https://user-images.githubusercontent.com/19935974/35458571-e00ff52e-02aa-11e8-8d0c-758824e48c50.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Still seeing this on Relatives review screen:

![2018-02-28-1](https://user-images.githubusercontent.com/19935974/36812536-7a359470-1c9f-11e8-998b-39a32539416f.png)

**Comment by bmallred** [comment]
This also appears to be happening on the review pages for:
 - Relationships
 - Financial record
 - Substance use

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
