### ISSUE TITLE
Foreign military - organization asterisks new line

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2528]
- [ ] Bring asterisks up to label

![screen shot 2018-01-29 at 9 57 11 am](https://user-images.githubusercontent.com/19935974/35516885-eb1820cc-04da-11e8-9356-74b40d14d28a.png)

**Comment by bmallred** [comment]
Same issue as #2527

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
