### ISSUE TITLE
Help icons and text - screen reader

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2629]
- [x] Help icons are reading as "link graphic" - change to "show help"
- [ ] Move focus to help info box on reveal after clicking "?"
- [ ] After user closes help bring focus back to input that help is related to (currently after using the close link the next tab goes to the "Skip to main content link)

**Comment by Jay-Neighbours-I72** [comment]
Related #1336

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
