### ISSUE TITLE
Missing label in employment record

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2686]
- [ ] Looks like a label is missing:

![screen shot 2018-02-28 at 2 05 57 pm](https://user-images.githubusercontent.com/19935974/36807292-8eea46a4-1c90-11e8-9b1a-580626695152.jpg)

**Comment by floresj** [comment]
Lies. It's an illusion.

**Comment by floresj** [comment]
@Jay-Neighbours-I72  Question.. maybe it's early. I don't see labels on any of our other telephone components. For instance,

![selection_797](https://user-images.githubusercontent.com/5938731/36980099-60a3db3c-2057-11e8-8583-1ed59458253f.png)

What should be the text there?

**Comment by Jay-Neighbours-I72** [comment]
You are right, there shouldn't be a label there at all per PDF guide.

**Comment by floresj** [comment]
Cool. Will remove :burrito:

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
