### ISSUE TITLE
Multiple input fields - accessibility 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2738]
Inputs with multiple fields (SSN, phone numbers) - need to be clear to screen readers which input they are in - example - "first 3 numbers, middle 3 numbers, last 4 numbers"
![screen shot 2018-03-19 at 3 05 48 pm](https://user-images.githubusercontent.com/19935974/37616652-05f463a6-2b87-11e8-8499-d8d393c98f31.jpg)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
