### ISSUE TITLE
Relative type options - accessibility 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2752]
- [ ] Sounds like JAWS is reading parts of code on these buttons (provide relative type" - "left bracket object object right bracket"

**Comment by bmallred** [comment]
#2778 did not actual resolve this (wrong issue number used)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
