### ISSUE TITLE
Error list - links not landing on proper location

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2767]
- [ ] Page is scrolling past error

In this example error is in phone number, this is where page landed:
![screen shot 2018-03-23 at 4 26 34 pm](https://user-images.githubusercontent.com/19935974/37851926-10e7b6cc-2eb7-11e8-99cc-d9a9adc8a956.jpg)

Error is here:
![screen shot 2018-03-23 at 4 27 32 pm](https://user-images.githubusercontent.com/19935974/37851939-196144ee-2eb7-11e8-8a5d-81648e8a30f7.jpg)

- [ ] Can the focus be placed in the input with the error for screen reader users?

**Comment by Jay-Neighbours-I72** [comment]
Also can these open an accordion item when error is within an accordion?

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
