### ISSUE TITLE
Info about you - empty email bug

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2768]
- [ ] When email is left empty there is an error on review screen. email is not required so should not throw error

![screen shot 2018-03-23 at 4 28 55 pm](https://user-images.githubusercontent.com/19935974/37852019-6629fd66-2eb7-11e8-9d79-e7bb0ea8269c.jpg)

**Comment by bmallred** [comment]
Just a note to self... Need to write an exception for validation here because it is just the accordion saying it is missing input. This section is the only use case for this in the application

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
