### ISSUE TITLE
Info about you error list - SSN

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2772]
After fixing a SSN error the nav dot and error list didn't update:

 
![screen shot 2018-03-23 at 4 36 05 pm](https://user-images.githubusercontent.com/19935974/37852276-5ff58f18-2eb8-11e8-8a6b-d451c0125d1e.jpg)
![screen shot 2018-03-23 at 4 36 10 pm](https://user-images.githubusercontent.com/19935974/37852277-6108da54-2eb8-11e8-9756-31ab233e14b3.jpg)

**Comment by Jay-Neighbours-I72** [comment]
I'm still seeing this on staging

![screen shot 2018-04-09 at 10 46 49 am](https://user-images.githubusercontent.com/19935974/38504686-592ea9ca-3be3-11e8-8476-199ab879fa4f.jpg)
![screen shot 2018-04-09 at 10 46 56 am](https://user-images.githubusercontent.com/19935974/38504688-593d9aca-3be3-11e8-9063-603fe2bb0de3.jpg)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
