### ISSUE TITLE
Review screen - red icon in nav update time

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2784]
Currently user have to leave the review screen and come back for this indicator to update.

Can it update and change to green when all errors are fixed?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72  do you mean once they have been resolved in the individual sections and **not** the review section?

Flow:
 1. Fill out sections with errors
 2. Go to review and notice errors
 3. Go back to sections and fix errors individually (not on the review page)

**Comment by Jay-Neighbours-I72** [comment]
No, sorry. I wasn't very descriptive.

1. I mean user is on review screen
2. Fixes errors on review screen
3. User expects the red dot to update to green when all errors are fixed

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
