### ISSUE TITLE
Data persistence - logging back in messaging

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2804]
When logging back in with saved data there is a bit of lag while data is being loaded.

I'd suggest some sort of loading message here "We are loading your saved data" . With the loading time users may be confused or worried their saved data is gone.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
