### ISSUE TITLE
Relatives - Cohabitant section showing error but all sections are complete

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2806]
On staging - data is under my log in test04:

- [ ] Cohabitant section is complete but showing an error
![screen shot 2018-03-29 at 2 04 42 pm](https://user-images.githubusercontent.com/19935974/38105535-4b3bb57e-335a-11e8-9142-61a0e32c52ee.png)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
