### ISSUE TITLE
Citizenship - accordion titles

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2825]
Foreign passport accordion titles are being truncated to 1 letter

![screen shot 2018-04-03 at 3 26 55 pm](https://user-images.githubusercontent.com/19935974/38271390-5c47bf0e-3754-11e8-8e65-eeefea21ca7b.jpg)
![screen shot 2018-04-03 at 3 27 02 pm](https://user-images.githubusercontent.com/19935974/38271392-5c5371c8-3754-11e8-86b2-31dea71a406c.jpg)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
