### ISSUE TITLE
Add asterisks to individual fields

### ISSUE THREAD

**Issue by pjsumm** [ryanhofdotgov/e-QIP-prototype-truetandem#2832]
As an eApp application I want to see asterisks for each data entry component that is required so that if I have a composite group of fields like an address or phone numbers, I see an asterisk for each component field of the group of fields.  

Acceptance Criteria
- [ ] Add asterisks to all required fields in a composite field group.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
