### ISSUE TITLE
SSN screen reader issue - IE 11 and Edge

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2835]
Edge & IE
- [ ] Users can keep typing numbers after confirmed inputs disappear
- [ ] Tabbing out of confirm input takes user to top of screen and skips the back/next buttons 
- [ ] Is there a way to force the screen reader to read the "Thanks for confirming" message after SSN is confirmed?

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
