### ISSUE TITLE
IE 11 and Edge nav scrolling issue

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2837]
- [ ] On shorter screens (with less content) the nav isn't responsive when trying to scroll down. It jumps up and down slightly but doesn't scroll down. Sometimes eventually it unlocks and scrolls

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
