### ISSUE TITLE
Accessibility - Address block - This address is links

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2847]
This address is links:
- [ ] In the US
- [ ] APO/FPO/DPO
- [ ] Outside the US

All 3 buttons are not reading the text, instead are reading brackets and other code

- [ ] Apt line is also doing the same thing

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
