### ISSUE TITLE
Other name used validation - error on birthday

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2866]
Currently an error is thrown when the from date is the same as DOB.

For a nickname used since birth this would be a valid answer.

- [ ] Can we not thrown an error on DOB but only throw error on date before DOB?

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
