### ISSUE TITLE
Address block - international address - 2 comments

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2867]
- [ ] After switching to international address an additional comment link was added (this was on schools page)

![screen shot 2018-04-16 at 3 55 26 pm](https://user-images.githubusercontent.com/19935974/38831863-b5d7a766-418e-11e8-88e7-b5c26ff50788.jpg)

**Comment by bmallred** [comment]
The bottom comment is for the entire address block whereas the one closer to *country* is for the country value.

@Jay-Neighbours-I72 do we need the comment on the address block? I don't see it in the content guide

**Comment by Jay-Neighbours-I72** [comment]
@bmallred Ahh I see. I don't think we need the comment on the full address block

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
