### ISSUE TITLE
Marital - phone number - "use my current phone number" button

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2868]
Looks like we are missing the "Use my current telephone number" button in the marriage, civil union, domestic partnership, and separated branches

This would be a text button and pull in current phone number (like the current address button)

![screen shot 2018-04-17 at 1 31 34 pm](https://user-images.githubusercontent.com/19935974/38886450-ffd692cc-4243-11e8-9062-30cf5c9fcf09.jpg)

**Comment by bmallred** [comment]
We need to determine what **current phone number** actually refers to since they may have multiple.

 - Is it just the first one off the list?
 - Are some phone numbers weighted by call time, type of phone number, domestic/international?

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
