### ISSUE TITLE
Data persistence additional test automation

### ISSUE THREAD

**Issue by pjsumm** [ryanhofdotgov/e-QIP-prototype-truetandem#2879]
There should be automated integration tests that exercise the API calls for persisting and reading back form data (`Save`, `AllSections`, `Section`). Data can be verified by db introspection directly, or via an API call. Test data should cover 90% (ideally all) sections/fields of the SF-86 (via one large/complete application or smaller test snippets, as appropriate). There is likely test data overlap between these tests and the one John is putting together for eQIP API submission.

The automated test priority is to execution pathways that are likely to lead to cause of errors seen by Paul, or were problems historically.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
