### ISSUE TITLE
Your history accordion item numbers

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2889]
Accordion item numbers are missing for:

- [ ] Where you have lived
- [ ] Employment activites
- [ ] Where you went to school

![screen shot 2018-04-23 at 10 58 03 am](https://user-images.githubusercontent.com/19935974/39134758-5c1100fe-46e5-11e8-984c-5b92416a1615.jpg)
![screen shot 2018-04-23 at 10 58 07 am](https://user-images.githubusercontent.com/19935974/39134760-5c480f5e-46e5-11e8-9e19-dfce2ab5bd79.jpg)
![screen shot 2018-04-23 at 10 58 11 am](https://user-images.githubusercontent.com/19935974/39134761-5c555f88-46e5-11e8-9715-306985adcba6.jpg)

**Comment by floresj** [comment]
Lies. They are there. They're just invisible.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
