### ISSUE TITLE
Relationships - marital - location of marriage not saving - Data Persistence

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [ryanhofdotgov/e-QIP-prototype-truetandem#2916]
- [ ] Marriage location not saving

![screen shot 2018-04-27 at 10 20 10 am](https://user-images.githubusercontent.com/19935974/39367514-f02c60ea-4a04-11e8-8e43-56598e5f364d.jpg)

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
