### ISSUE TITLE
How do we handle validation/translation of accented characters

### ISSUE THREAD

**Issue by bmallred** [ryanhofdotgov/e-QIP-prototype-truetandem#371]
Brought over from #294

**Comment by bmallred** [comment]
Need to find out if our back-end systems where everything will come to rest handles this.

**Comment by pjsumm** [comment]
Need to research how the current system handles this situation.  If required for eApp, need to make sure the form's regular expressions can handle special characters either client side or server side.

**Comment by pjsumm** [comment]
We'll use this as a test case for testing data submitted to eqip via web services to determine how to support translation with the legacy system.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
