### ISSUE TITLE
Prevent accidental clicking of "estimated" checkbox on leaving date fields

### ISSUE THREAD

**Issue by bmallred** [ryanhofdotgov/e-QIP-prototype-truetandem#374]
Brought over from #294

**Comment by pjsumm** [comment]
Team reviewed and decide to keep it in the icebox for now.  User is tabbing through date fields and if there is an "estimated" checkbox after the date field.  Concern is that working around by changing tabbing could accidentally affect accessibility with screen readers and such.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
