### ISSUE TITLE
Storyboard Form Usability Instructions

### ISSUE THREAD

**Issue by pjsumm** [ryanhofdotgov/e-QIP-prototype-truetandem#653]
As an eApp Applicant I want to see basic instructions for how the eApp online SF86 form works so that I have a basic understanding of the form's features and behavior before I begin filling in information.

Instructions:
- Save
- Progress notifications
- Navigation 
- Mobile layout

**Comment by bmallred** [comment]
Refer to #652

**Comment by bmallred** [comment]
Shelved due to reasoning of if there are questions it may need to be revised instead of explicit instructions.

@pjsumm feedback on this is welcome!

**Comment by pjsumm** [comment]
keeping this issue on Ice.  the preference is to create an interface that is completely intuitive and self-explanatory.  If this is  needed, will keep to the end.  Danger in doing this type of help is it becomes a crutch to help explain bad UI design.  Best to fix the issue in the UI rather than add help.  However, if any such items need to be explained, we can add that type of help as a last resort.

**Comment by ryanhofdotgov** [comment]
Kamino closed and cloned this issue to 18F/e-QIP-prototype
